# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23caa4128ad2be40709a444ef2fa3a5130bd58af71bb569a99f52800ac7ee2030f72bf9fa371c4010eba0a757ae36932783c070401d0cd56ba63fbabe8a6851

test:
  secret_key_base: 67ee577ec18bbc11942a50add6877970f24dafcd7d9d7b40d866267318b79f38b8ccfebbb88fbfc75ba4721efa6018a708c447560ec44edf996b945a466472d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
